### PR TITLE
Add PreTokenizers

### PR DESCRIPTION
**Pull request by petergoldstein**
This PR is an attempt to add the set of PreTokenizers currently in the Python library.  It successfully adds those PreTokenizers, but there are a few concerns and questions I wanted to call out.

1. I wasn't able to figure out how to implement the methods implemented with [getter!](https://github.com/huggingface/tokenizers/blob/fa66caf0abff16bae2213658ffa3e969c5445750/bindings/python/src/pre_tokenizers.rs#L186) and [setter!](https://github.com/huggingface/tokenizers/blob/fa66caf0abff16bae2213658ffa3e969c5445750/bindings/python/src/pre_tokenizers.rs#L202) on the PreTokenizers that support such methods ([example method](https://github.com/huggingface/tokenizers/blob/fa66caf0abff16bae2213658ffa3e969c5445750/bindings/python/src/pre_tokenizers.rs#L476)).  If you can give me some guidance I may be able to implement this.
2. I skipped trying to get the `Split` pretokenizer to accept a Regex, because there was no native Regex mapping in Magnus.  I figured that could be added later.
3. I followed the pattern for the existing PreTokenizers (`Whitespace`), but this leaves the `Tokenizers` module crowded with a number of classes that are PreTokenizers, but are not clearly PreTokenizers from their names.  It may be desirable to create a PreTokenizers module (which is the pattern in place in the Python library)

Thoughts?

### CODE REVIEW

**Comment by petergoldstein** [comment]
@ankane Note that because of (3) I'm already running into a name conflict as I attempt to implement the normalizers.  There's a `Strip` pre-tokenizer and a `Strip` normalizer.  I think we should think about adding submodules.

**Comment by ankane** [comment]
Thanks @petergoldstein.

1. Will take a look when I have a chance
2. Sounds good
3. Agree we should either do that or add a suffix (`StripPreTokenizer`, `StripNormalizer`) before the release. I feel like keeping it flat feels more Ruby-like (although with other projects I've just followed Python). Feel free to use something like `Strip2` for the normalizer for now.

Also, for custom argument types like `RbSplitDelimiterBehavior`, this approach works well: 4294d64fb47fa2544bcd1ab107a62699bc2e28ff

**Comment by ankane** [comment]
For 1, I added the `getter!` and `setter!` macros for models (the Rust methods need to be defined on the parent class - [example](https://github.com/ankane/tokenizers-ruby/blob/ecec16f142f2f3f0d1a665a56073a7df289bb823/ext/tokenizers/src/models.rs#L300-L305)). I imagine it'll be similar for pre-tokenizers.

**Comment by petergoldstein** [comment]
@ankane Great.  I should be able to use those as templates tomorrow.  I'll ping you if anything is unclear.  Thanks.

**Pull request merged**
