### PR TITLE
Use `rake-compiler` and `rb-sys` for build

### PR DESCRIPTION
**Pull request by ianks**
This PR changes the build system to use [rb-sys](https://github.com/oxidize-rb/rb-sys) and [rake-compiler](https://github.com/rake-compiler/rake-compiler) to build the gem. With this change, it will be possible to publish native binaries of the gem so that consumers will not have to maintain a rust toolchain for deployment.

The actual publishing of the gem is not handled by this PR, but the `cross-build` Github action will build a bunch of `*.gem` files which can pushed to Rubygems.

❤️

### CODE REVIEW

**Comment by kojix2** [comment]
I hope this wonderful gem will be easy to install.

**Comment by ankane** [comment]
Hey @ianks, sorry for the delay. Switched to `rb_sys` + `rake-compiler` and the directory structure from https://github.com/rubygems/rubygems/pull/5613 in the commit above (wanted to do this separately from precompiling). Will hopefully try out the `cross-gem-action` soon.

Thanks again for all the work on `rb_sys` and driving this!

**Comment by ankane** [comment]
Hey @ianks,

Added precompiling for a few platforms in the commit above (it currently fails on `aarch64-linux`  since OpenSSL isn't available). It'd be nice if `rb_sys` provided a way to cross-compile locally as well (if it doesn't already, like `rake-compiler-dock`).

Thanks again for all the work you've done on Ruby + Rust!

**Comment by ankane** [comment]
Just released 0.2.0 with precompiled versions for Mac and x86-64 Linux.

**Comment by ianks** [comment]
🔥 🔥 🔥 

> Added precompiling for a few platforms in the commit above (it currently fails on aarch64-linux since OpenSSL isn't available). It'd be nice if rb_sys provided a way to cross-compile locally as well (if it doesn't already, like rake-compiler-dock).

Just [literally published a fix for that today in v0.9.47](https://github.com/oxidize-rb/rb-sys/commit/d5882e3988400806a61f41d348a30db10a82de6c). Hopefully that fixed it!

> . It'd be nice if rb_sys provided a way to cross-compile locally as well (if it doesn't already, like rake-compiler-dock).

Ah yes, it is actually just `rake-compiler-dock` under the hood so it should work fine. Admittedly, I don't do it often because currently `arm64` builds for rcd aren't published. And since I'm on an M1, they are slowwwwww. [You can see how it's done here](https://github.com/oxidize-rb/rb-sys/blob/fce5ee27bb0738d399dc07e767b7692ce1b8b675/script/rcd#L6).

**Comment by ankane** [comment]
Thanks @ianks!

Tried v0.9.47, but think it may solve a different issue (the `aarch64-linux` failure is due to a [missing header](https://github.com/ankane/tokenizers-ruby/actions/runs/3672037562/jobs/6207832005) required by `openssl-sys` - need to spend more time on it).

**Comment by ianks** [comment]
Oof yeah that’s a bit of a doozy. Providing a cross platform version of OpenSSL should be possible in the `setup` of cross gem action, but ideally the dep on openssl-sys could be removed entirely in favor of rustls. I think this may be coming from the `http` feature of the tokenizers crate? Not sure though.

**Pull request closed without merging**
