### PR TITLE
Fill out the set of getters and setters

### PR DESCRIPTION
**Pull request by petergoldstein**

### CODE REVIEW

**Comment by petergoldstein** [comment]
@ankane So I think that now this is merged, the gem is essentially feature complete with the Python library.  Are there any major gaps you're aware of?

**Comment by ankane** [comment]
Nice, I think that's most of the API. Going to try and get the `Sequence` classes working later today and make sure all these examples run: https://huggingface.co/docs/tokenizers/pipeline

**Comment by ankane** [comment]
New release is out. Thanks again for all the great PRs!

**Comment by petergoldstein** [comment]
Great.  My pleasure.

**Pull request merged**
